name: CI

on: [push, repository_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
    - name: Install dependencies
      run: yarn install --prod --pure-lockfile
    - name: Build Gatsby Site
      uses: jzweifel/gatsby-cli-github-action@master
      env:
          GHOST_API_URL: "https://ghostzecloud.azurewebsites.net"
          GHOST_CONTENT_API_KEY: ${{ secrets.GHOST_CONTENT_API_KEY }}
      with:
        gatsby-arg: build
    - name: Commit files
      run: |
        cd public 
        git init
        git add .
        git remote add origin https://github.com/zecloud/zecloud.github.io.git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Publish new verion" -a
    - name: Deploy
      uses: s0/git-publish-subdir-action@mpublic
      env:
        REPO: git@github.com:zecloud/zecloud.github.io.git
        BRANCH: master
        FOLDER: public
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY}}
    
