name: CI

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [build-application]
      
# on: [push, repository_dispatch]
#   branches:
#     - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: yarn install --prod --pure-lockfile
    - name: Build Gatsby Site
      uses: zecloud/gatsby-cli-github-action@master
      env:
          GATSBY_PORTAL_URL: ${{ secrets.GHOST_API_URL }}
          GHOST_API_URL: ${{ secrets.GHOST_API_URL }}
          GHOST_CONTENT_API_KEY: ${{ secrets.GHOST_CONTENT_API_KEY }}
      with:
        gatsby-arg: build
    - name: Deploy
      uses: s0/git-publish-subdir-action@master
      env:
        REPO: git@github.com:zecloud/zecloud.github.io.git
        BRANCH: master
        FOLDER: public
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY}}
    
